environment:
  PYTHON: "C:\\Python36-x64"

install:
  - SET "PYTHONHOME=%PYTHON%"
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.9/latest/ pyside2 --trusted-host download.qt.io
  - pip install flake8 pytest pytest-cov codecov

build: off

test_script:
  - flake8
  - python -m pytest --cov=quina

after_test:
  - codecov --token=88e58cf1-53c3-4dfe-b25d-68d6c17bbb8b
