environment:
  CONDA_NPY: 113
  CONDA_PY: 36
  CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda.exe install -c conda-forge --yes --quiet PySide2
  - cmd: conda.exe install --yes --file requirements.txt
  - cmd: pip install flake8 pytest pytest-cov codecov

build: off

test_script:
  - flake8
  - python -m pytest --cov=quina

after_test:
  - codecov --token=88e58cf1-53c3-4dfe-b25d-68d6c17bbb8b
